/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#8bf088",
        "on-secondary-container": "#217128",
        "secondary-fixed": "#a3f69c",
        "primary-fixed": "#d6e3ff",
        "surface-bright": "#f8f9fb",
        "inverse-on-surface": "#eff1f3",
        "secondary-container": "#a0f399",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "outline": "#727783",
        "error": "#ba1a1a",
        "tertiary": "#005413",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed-dim": "#88d982",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001b3d",
        "surface": "#f8f9fb",
        "on-secondary-fixed": "#002204",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed-dim": "#78dc77",
        "inverse-surface": "#2d3133",
        "background": "#f8f9fb",
        "on-tertiary-fixed-variant": "#005313",
        "secondary": "#1b6d24",
        "surface-container": "#eceef0",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#94f990",
        "on-surface-variant": "#424752",
        "on-tertiary-fixed": "#002204",
        "on-secondary-fixed-variant": "#005312",
        "tertiary-container": "#006f1d",
        "inverse-primary": "#a9c7ff",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#a9c7ff",
        "on-primary-fixed-variant": "#00468c",
        "outline-variant": "#c2c6d4",
        "on-primary-container": "#c8daff",
        "primary": "#00478d",
        "surface-tint": "#005db6",
        "primary-container": "#005eb8"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
